---
title: "lab09-hongling-lei"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(testthat)
```

### Part 2) Basics of String Manipulation*
```{r}
head(USArrests)
```
```{r}
states <- rownames(USArrests)
head(states)
```
```{r}
nchar(states)
```
```{r}
tolower(states)
```
```{r}
toupper(states)
```
```{r}
casefold(states)
```
```{r}
num_chars <- nchar(states)
char_freqs <- table(num_chars)
barplot(char_freqs)
```
```{r}
paste('Pumpkin', 'Pie')
```
```{r}
paste('a', 'b', 'c', 'd', 'e')
```
```{r}
paste('a', 'b', 'c', 'd', 'e', sep = '-')
```
```{r}
paste('a', 1:5, sep = '.')
```
```{r}
# paste0() -vs- paste(..., sep = "")
paste0('Pumpkin', 'Pie')
paste('Pumpkin', 'Pie', sep = '')
```
```{r}
# paste0() is also vectorized
paste0('a', 1:5)
```

### Your Turn*: paste()
```{r}
first_5 <- head(states, 5)
paste(first_5, nchar(first_5), sep = " = ")
```
```{r}
paste(first_5, collapse = "")
```

### Your Turn*: Permutations

Find the number of permutations that can be formed by using all the given letters in ALABAMA. For instance: "ALAMABA", "AMALABA", "AAAABML".
```{r}
table(strsplit("ALABAMA", split = ""))
```
```{r}
# There are 4A, 1B, 1L, 1M in "ALABAMA"
# First we have 4 As: _A_A_A_A_
# Then insert B: C51 =  5, e.g. _A_B_A_A_A_
# Then insert L: C61 = 6, e.g. _A_B_A_L_A_A_
# Finally inset M: C71 = 7, e.g. _A_B_A_L_A_A_M_ => ABALAAM
# So the total number of permutations is 5 x 6 x 7 = 210
```
∴ Number of permutations = 210


### Substring
```{r}
# extract first 3 characters
substr('Berkeley', 1, 3)
```
```{r}
# Use substr() to shorten the state names using the first 3-letters:
substr(states, 1, 3)
```
```{r}
# Use substr() to shorten the state names using the last 3-letters:
substr(states, nchar(states)-2, nchar(states))
```
```{r}
# How would you shorten the state names using the first letter and the last 3-letters? For instance: "Aama" "Aska" "Aona" "Asas" etc.
paste0(substr(states, 1, 1), substr(states, nchar(states)-2, nchar(states)))
```

### Your Turn*: Converting Temperatures
```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')
```

```{r}
# Rewrite temp_convert() such that the argument to can be given in upper or lower case letters. For instance, the following three calls should be equivalent:

temp_convert <- function(x = 1, to = "celsius") {
  if (tolower(to) == "celsius"){
    to = "celsius"
  }
  if (tolower(to) == "kelvin"){
    to = "kelvin"
  }
  if (tolower(to) == "reaumur"){
    to = "reaumur"
  }
  if (tolower(to) == "rankine"){
    to = "rankine"
  }
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

# test:
temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

### Your Turn*: Names of files
```{r}
# Imagine that you need to generate the names of 10 data .csv files. All the files have the same prefix name but each of them has a different number: file1.csv, file2.csv, … , file10.csv.

# How can you generate a character vector with these names in R? Come up with at least three different ways to get such a vector:

# way1
A1 = paste("file", 1:10, sep = ".")
A1
```
```{r}
# way2
A2 = paste0("file.", 1:10)
A2
```
```{r}
# way3
X = rep("file", 10)
Y = c(1:10)
A3 = paste(X, Y, sep = ".")
A3
```
```{r}
# way4
A4 = rep("file.1", 10)
for (i in 1:10){
  A4[i] = paste0("file.", i)
}
A4
```

```{r}
# Now imagine that you need to rename the characters file into dataset. In other words, you want the vector of file names to look like this: dataset1.csv, dataset2.csv, … , dataset10.csv. Take the previous vector of file names and rename its elements:
for (i in 1:10){
  A4[i] = paste0("dataset", i, ".csv")
}
A4
```

### Your turn*: cat()
```{r}
# modify

# name of output file
outfile <- "output.txt"

# writing to 'outfile.txt'
cat("---", file = outfile)
# insert new lines
cat("\n", file = outfile, append = TRUE)
cat('title: "A random .txt file"', file = "output.txt", append = TRUE)

cat("\n", file = outfile, append = TRUE)
cat('author: "Hongling Lei"', file = outfile, append = TRUE)

cat("\n", file = outfile, append = TRUE)
cat('date: "4/4/2019"', file = outfile, append = TRUE)

cat("\n", file = outfile, append = TRUE)
cat('output: "html_document"', file = outfile, append = TRUE)

cat("\n", file = outfile, append = TRUE)
cat("---", file = outfile, append = TRUE)

cat("\n\n", file = outfile, append = TRUE)
cat("This is the first line", file = outfile, append = TRUE)

cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n", file = outfile, append = TRUE)
```


### Your Turn*: Valid Color Names
```{r}
# my is_color() function:
#' @title is_color function
#' @description tests if a given name-in English-is a valid R color
#' @param color the color you typed in
#' @return TRUE or FALSE

is_color <- function(color){
  return(is.element(color, colors()))
}

# test it:
is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE
```





